# ---------------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------------

name: kubernetes

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.adoc'
      - 'KEYS'
      - 'LICENSE'
      - 'NOTICE'
  push:
    branches:
      - main
    paths-ignore:
      - '**.adoc'
      - 'KEYS'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      YAKS_IMAGE_NAME: "docker.io/citrusframework/yaks"
      YAKS_VERSION: "0.13.0"
      YAKS_RUN_OPTIONS: "--timeout=240s"
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Kind Cluster
      uses: container-tools/kind-action@v1
      with:
        version: v0.14.0
        node_image: kindest/node:v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae
    - name: Info
      run: |
        kubectl version
        kubectl cluster-info
        kubectl describe nodes
    - name: Camel K Tools
      uses: container-tools/camel-k-action@v1
    - name: Install Camel K
      run: |
        # Configure install options
        export KAMEL_INSTALL_BUILD_PUBLISH_STRATEGY=Spectrum
        export KAMEL_INSTALL_REGISTRY=$KIND_REGISTRY
        export KAMEL_INSTALL_REGISTRY_INSECURE=true
        
        kamel install --global --olm=false --operator-env-vars KAMEL_BASE_IMAGE=docker.io/eclipse-temurin:11
    - name: YAKS tools
      uses: citrusframework/yaks-install-action@v1.0
      with:
        version: v${{ env.YAKS_VERSION }}
    - name: Install YAKS
      run: |
        yaks install --operator-image $YAKS_IMAGE_NAME:$YAKS_VERSION
    - name: Run Tests
      run: |
        yaks run test/fruit-service.feature $YAKS_RUN_OPTIONS --env FRUIT_SERVICE_URL='http://fruit-service.${YAKS_NAMESPACE}'
